--  -------------------------------------------------- --
--  Generated by Enterprise Architect Version 7.1.833--
--  Created On : dinsdag, 09 december, 2014 --
--  DBMS       : PostgreSQL --
--  -------------------------------------------------- --






-- Create Tables --
CREATE TABLE vrn.gebiedbeheer_landelijk ( 
	id serial NOT NULL,
	identificatie text NOT NULL,    -- IMNA id --
	job_id bigint,
	gfid text,
	beheerpakket text,
	status_beheer text NOT NULL,
	doelbeheer text NOT NULL,    -- Alleen waarden invullen uit codelijst DoelRealisatie. Indien meerdere waarden uit de  codelijst van toepassing zijn op  hetzelfde object, worden deze door  middel van een komma gescheiden  waarde ingevoerd.  
-- Bijvoorbeeld Natura2000;NURG --
	imna_bronhouder text NOT NULL,
	contractnummer integer,
	eenheidnummer text,
	geometrie geometry NOT NULL,
	relatienummer integer,
	type_beheerder text NOT NULL,
	begintijd timestamp NOT NULL,
	eindtijd timestamp
)
;
COMMENT ON TABLE vrn.gebiedbeheer_landelijk
    IS 'provincie aan BIJ12'
;
COMMENT ON COLUMN vrn.gebiedbeheer_landelijk.identificatie
    IS 'IMNA id'
;
COMMENT ON COLUMN vrn.gebiedbeheer_landelijk.doelbeheer
    IS 'Alleen waarden invullen uit codelijst DoelRealisatie. Indien meerdere waarden uit de  codelijst van toepassing zijn op  hetzelfde object, worden deze door  middel van een komma gescheiden  waarde ingevoerd.  
-- Bijvoorbeeld Natura2000;NURG'
;

CREATE TABLE vrn.gebiedbeheer_provinciaal ( 
	id serial NOT NULL,
	identificatie text NOT NULL,    -- IMNA id --
	job_id bigint,
	gfid text,
	beheerpakket text,
	status_beheer text NOT NULL,
	doelbeheer text NOT NULL,    -- Alleen waarden invullen uit codelijst DoelRealisatie. Indien meerdere waarden uit de  codelijst van toepassing zijn op  hetzelfde object, worden deze door  middel van een komma gescheiden  waarde ingevoerd.  
-- Bijvoorbeeld Natura2000;NURG --
	imna_bronhouder text NOT NULL,
	contractnummer integer,
	eenheidnummer text,
	geometrie geometry NOT NULL,
	relatienummer integer,
	type_beheerder text NOT NULL,
	begintijd timestamp NOT NULL,
	eindtijd timestamp
)
;
COMMENT ON TABLE vrn.gebiedbeheer_provinciaal
    IS 'natuurbeheerder/RVO aan provincie'
;
COMMENT ON COLUMN vrn.gebiedbeheer_provinciaal.identificatie
    IS 'IMNA id'
;
COMMENT ON COLUMN vrn.gebiedbeheer_provinciaal.doelbeheer
    IS 'Alleen waarden invullen uit codelijst DoelRealisatie. Indien meerdere waarden uit de  codelijst van toepassing zijn op  hetzelfde object, worden deze door  middel van een komma gescheiden  waarde ingevoerd.  
-- Bijvoorbeeld Natura2000;NURG'
;

CREATE TABLE vrn.gebiedinrichting_landelijk ( 
	id serial NOT NULL,
	identificatie text NOT NULL,    -- IMNA id --
	job_id bigint,
	gfid text,
	imna_bronhouder text NOT NULL,
	contractnummer integer,
	geometrie geometry NOT NULL,
	relatienummer integer,
	status_inrichting text NOT NULL,
	doelinrichting text,
	type_beheerder text NOT NULL,
	begintijd timestamp NOT NULL,
	eindtijd timestamp
)
;
COMMENT ON COLUMN vrn.gebiedinrichting_landelijk.identificatie
    IS 'IMNA id'
;

CREATE TABLE vrn.gebiedinrichting_provinciaal ( 
	id serial NOT NULL,
	identificatie text NOT NULL,    -- IMNA id --
	job_id bigint,
	gfid text,
	imna_bronhouder text NOT NULL,
	contractnummer integer,
	geometrie geometry NOT NULL,
	relatienummer integer,
	status_inrichting text NOT NULL,
	doelinrichting text NOT NULL,
	type_beheerder text NOT NULL,
	begintijd timestamp NOT NULL,
	eindtijd timestamp
)
;
COMMENT ON COLUMN vrn.gebiedinrichting_provinciaal.identificatie
    IS 'IMNA id'
;

CREATE TABLE vrn.gebiedverwerving_landelijk ( 
	id serial NOT NULL,
	identificatie text NOT NULL,    -- IMNA id --
	job_id bigint,
	gfid text,
	imna_bronhouder text NOT NULL,
	contractnummer integer,
	geometrie geometry NOT NULL,
	relatienummer integer,
	status_verwerving text NOT NULL,
	doelverwerving text,
	type_eigenaar text NOT NULL,
	begintijd timestamp NOT NULL,
	eindtijd timestamp
)
;
COMMENT ON COLUMN vrn.gebiedverwerving_landelijk.identificatie
    IS 'IMNA id'
;

CREATE TABLE vrn.gebiedverwerving_provinciaal ( 
	id serial NOT NULL,
	identificatie text NOT NULL,    -- IMNA id --
	job_id bigint,
	gfid text,
	imna_bronhouder text NOT NULL,
	contractnummer integer,
	geometrie geometry NOT NULL,
	relatienummer integer,
	status_verwerving text NOT NULL,
	doelverwerving text,
	type_eigenaar text NOT NULL,
	begintijd timestamp NOT NULL,
	eindtijd timestamp
)
;
COMMENT ON COLUMN vrn.gebiedverwerving_provinciaal.identificatie
    IS 'IMNA id'
;


-- Create Primary Key Constraints --
ALTER TABLE vrn.gebiedbeheer_landelijk ADD CONSTRAINT PK_gebiedbeheer_landelijk 
	PRIMARY KEY (id)
;


ALTER TABLE vrn.gebiedbeheer_provinciaal ADD CONSTRAINT PK_gebiedbeheer_provinciaal 
	PRIMARY KEY (id)
;


ALTER TABLE vrn.gebiedinrichting_landelijk ADD CONSTRAINT PK_gebiedinrichting_landelijk 
	PRIMARY KEY (id)
;


ALTER TABLE vrn.gebiedinrichting_provinciaal ADD CONSTRAINT PK_gebiedinrichting_provinciaal 
	PRIMARY KEY (id)
;


ALTER TABLE vrn.gebiedverwerving_landelijk ADD CONSTRAINT PK_gebiedverwerving_landelijk 
	PRIMARY KEY (id)
;


ALTER TABLE vrn.gebiedverwerving_provinciaal ADD CONSTRAINT PK_gebiedverwerving_provinciaal 
	PRIMARY KEY (id)
;



-- Create Indexes --
ALTER TABLE vrn.gebiedbeheer_landelijk
	ADD CONSTRAINT UQ_gebiedbeheer_landelijk_identificatie UNIQUE (identificatie)
;
ALTER TABLE vrn.gebiedbeheer_provinciaal
	ADD CONSTRAINT UQ_gebiedbeheer_provinciaal_identificatie UNIQUE (identificatie)
;
ALTER TABLE vrn.gebiedinrichting_landelijk
	ADD CONSTRAINT UQ_gebiedinrichting_landelijk_identificatie UNIQUE (identificatie)
;
ALTER TABLE vrn.gebiedinrichting_provinciaal
	ADD CONSTRAINT UQ_gebiedinrichting_provinciaal_identificatie UNIQUE (identificatie)
;
ALTER TABLE vrn.gebiedverwerving_landelijk
	ADD CONSTRAINT UQ_gebiedverwerving_landelijk_identificatie UNIQUE (identificatie)
;
ALTER TABLE vrn.gebiedverwerving_provinciaal
	ADD CONSTRAINT UQ_gebiedverwerving_provinciaal_identificatie UNIQUE (identificatie)
; 